[project]
name = "feems-mcp-server"
version = "0.1.0"
description = "MCP server for FEEMS"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=0.1.0",
    "feems>=1.0.0", 
    "pandas",
    "numpy"
]

[tool.setuptools.packages.find]
where = ["."]
